export const exchangeRate = [
  {
    id: 1,
    country: "United States",
    currency: "USD",
    currency_name: "United States Dollar",
    exchange_rate_to_NPR: 133.44,
    flag: "🇺🇸",
  },
  {
    id: 2,
    country: "Australia",
    currency: "AUD",
    currency_name: "Australian Dollar",
    exchange_rate_to_NPR: 89.01,
    flag: "🇦🇺",
  },
  {
    id: 3,
    country: "Canada",
    currency: "CAD",
    currency_name: "Canadian Dollar",
    exchange_rate_to_NPR: 97.52,
    flag: "🇨🇦",
  },
  {
    id: 4,
    country: "Japan",
    currency: "JPY",
    currency_name: "Japanese Yen",
    exchange_rate_to_NPR: 1.23,
    flag: "🇯🇵",
  },
  {
    id: 5,
    country: "South Korea",
    currency: "KRW",
    currency_name: "South Korean Won",
    exchange_rate_to_NPR: 0.10,
    flag: "🇰🇷",
  },
  {
    id: 6,
    country: "United Kingdom",
    currency: "GBP",
    currency_name: "Pound Sterling",
    exchange_rate_to_NPR: 170.58,
    flag: "🇬🇧",
  },
  {
    id: 7,
    country: "Portugal",
    currency: "EUR",
    currency_name: "Euro",
    exchange_rate_to_NPR: 147.89,
    flag: "🇵🇹",
  },
  {
    id: 8,
    country: "France",
    currency: "EUR",
    currency_name: "Euro",
    exchange_rate_to_NPR: 147.89,
    flag: "🇫🇷",
  },
  {
    id: 9,
    country: "Denmark",
    currency: "DKK",
    currency_name: "Danish Krone",
    exchange_rate_to_NPR: 19.86,
    flag: "🇩🇰",
  },
  {
    id: 10,
    country: "Germany",
    currency: "EUR",
    currency_name: "Euro",
    exchange_rate_to_NPR: 147.89,
    flag: "🇩🇪",
  },
  {
    id: 11,
    country: "China",
    currency: "CNY",
    currency_name: "Chinese Yuan",
    exchange_rate_to_NPR: 19.34,
    flag: "🇨🇳",
  },
  {
    id: 12,
    country: "Switzerland",
    currency: "CHF",
    currency_name: "Swiss Franc",
    exchange_rate_to_NPR: 152.45,
    flag: "🇨🇭",
  },
  {
    id: 13,
    country: "Italy",
    currency: "EUR",
    currency_name: "Euro",
    exchange_rate_to_NPR: 147.89,
    flag: "🇮🇹",
  },
  {
    id: 14,
    country: "India",
    currency: "INR",
    currency_name: "Indian Rupee",
    exchange_rate_to_NPR: 1.60,
    flag: "🇮🇳",
  },
  {
    id: 15,
    country: "Brazil",
    currency: "BRL",
    currency_name: "Brazilian Real",
    exchange_rate_to_NPR: 26.47,
    flag: "🇧🇷",
  },
  {
    id: 16,
    country: "Russia",
    currency: "RUB",
    currency_name: "Russian Ruble",
    exchange_rate_to_NPR: 1.78,
    flag: "🇷🇺",
  },
  {
    id: 17,
    country: "South Africa",
    currency: "ZAR",
    currency_name: "South African Rand",
    exchange_rate_to_NPR: 8.98,
    flag: "🇿🇦",
  },
  {
    id: 18,
    country: "Mexico",
    currency: "MXN",
    currency_name: "Mexican Peso",
    exchange_rate_to_NPR: 6.69,
    flag: "🇲🇽",
  },
  {
    id: 19,
    country: "Saudi Arabia",
    currency: "SAR",
    currency_name: "Saudi Riyal",
    exchange_rate_to_NPR: 35.56,
    flag: "🇸🇦",
  },
  {
    id: 20,
    country: "Turkey",
    currency: "TRY",
    currency_name: "Turkish Lira",
    exchange_rate_to_NPR: 4.91,
    flag: "🇹🇷",
  },
  {
    id: 21,
    country: "New Zealand",
    currency: "NZD",
    currency_name: "New Zealand Dollar",
    exchange_rate_to_NPR: 82.43,
    flag: "🇳🇿",
  },
  {
    id: 22,
    country: "Singapore",
    currency: "SGD",
    currency_name: "Singapore Dollar",
    exchange_rate_to_NPR: 98.34,
    flag: "🇸🇬",
  },
  {
    id: 23,
    country: "Malaysia",
    currency: "MYR",
    currency_name: "Malaysian Ringgit",
    exchange_rate_to_NPR: 31.28,
    flag: "🇲🇾",
  },
  {
    id: 24,
    country: "Thailand",
    currency: "THB",
    currency_name: "Thai Baht",
    exchange_rate_to_NPR: 4.07,
    flag: "🇹🇭",
  },
  {
    id: 25,
    country: "Indonesia",
    currency: "IDR",
    currency_name: "Indonesian Rupiah",
    exchange_rate_to_NPR: 0.0092,
    flag: "🇮🇩",
  },
];
